services:
  app:
    container_name: ecommerce_prod
    build:
      context: .
      target: production
    ports:
      - '5173:5173'
    environment:
      NODE_ENV: production
    restart: unless-stopped
